### ISSUE TITLE
Publish on GNOME Shell Extensions website

### ISSUE THREAD

**Issue by jazzzz** [johannesjo/gnome-shell-extension-window-session-manager#1]
It would be nice if this extension could be installed from https://extensions.gnome.org/

**Comment by johannesjo** [comment]
Yes I agree. Problem is, that it contains a binary and thus can't be uploaded to the site. I would love to find another way, but running the library directly in the weird gnome shell js context seems almost impossible as things like exec and spawn, as well as the x11 bindings are not available. I'm glad for any suggestion!

**Comment by nafg** [comment]
You could instruct users to install the binary themselves...

**Comment by johannesjo** [comment]
@nafg: that's actually not a bad idea. Maybe there is even a way to download it for them.

**Comment by johannesjo** [comment]
It's done. Just waiting for approvement:
https://extensions.gnome.org/extension/1323/window-session-manager/

**Comment by nafg** [comment]
I've seen at least one extension that does that (instructs users to install X... I think it was actually a system package)

**Comment by johannesjo** [comment]
@nafg yes. The sensors extension does it for example. Could you maybe check if you can install it properly via the extension page?

**Comment by nafg** [comment]
I get a 404

**Comment by johannesjo** [comment]
Thanks for checking! Interesting. Seems like it needs to be approved first to show up... Not sure how the process works there...
