### ISSUE TITLE
Tabs on 'gnome-terminal' not restored?

### ISSUE THREAD

**Issue by ari-paavo-seitsonen** [johannesjo/gnome-shell-extension-window-session-manager#12]
Hello,

  I just had my first attempt with the package - very nice, thank you! - but encountered some issues; the first one, multiple instances of FireFox instead of a single one (which can be then used to "recover previous session") is apparently on its way to be fixed, but the second one was the missing tabs on 'gnome-terminal' when trying to recover the session. Having tens of windows, each with multiple tabs, this is quite a problem for me (I have been using 'roxterm' until now, the only application where I have found the option of saving the session, but this one is no longer maintained).

    Greetings and thank you in advance for any consideration!

**Comment by johannesjo** [comment]
Hey there! Thanks for taking your time. I thought about this one before, but as tabs are managed differently for each application it's impossible to find a generic solution for this problem, not to speak of a behavior which would fit all different use cases and expectations. 

If the application allows for it you can edit your session config manually to restore specific tabs via command line flags. Have a look here for the gnome terminal:
https://stackoverflow.com/questions/1188959/open-a-new-tab-in-gnome-terminal-using-command-line

When editing the session config look for the excutableFile property and delete the desktopFilePath property for the entry you want to adjust.
