### ISSUE TITLE
Selectively save a single stack of windows

### ISSUE THREAD

**Issue by ghost** [johannesjo/gnome-shell-extension-window-session-manager#14]
I don't know if this is a functionality provided by some other tool (I have looked, if it is please do tell) but I just have a bunch of images/documents open with FEH and I want to be able to restore them with minimal effort after a reboot.

Is there a way to do this?

**Comment by johannesjo** [comment]
Hey there! Thanks for opening up this issue. Are the images you're opening always the same ones or are they different every time?

**Comment by ghost** [comment]
I gave up on a gnome solution and ended up with this working solution:

```
ps aux|grep -oP "[f]eh.*" >~/feh_restore_session
sed -i 's_/_"/_;s/$/" \&/;1i#!/bin/bash' ~/feh_restore_session
```


then just bash ~/feh_restore_session after reboot.

**Comment by johannesjo** [comment]
@MoorayJenkins thanks for sharing! Interesting solution. You probably can combine this with lwsm (the command line tool) to restore the window positions afterwards. Ordering might not be ideal though..
