### ISSUE TITLE
Active in Tweak Tools, but no indicator icon

### ISSUE THREAD

**Issue by NouGithub** [johannesjo/gnome-shell-extension-window-session-manager#2]
Perhaps installed it incorrectly, though I did follow your instructions.

**Comment by johannesjo** [comment]
Hello! Thanks for reporting! Could you maybe provide some additional info? You can open the debug console by pressing Alt+F2 and typing `lg` at the prompt. Then you click on extensions an check for the window session manager. Are there any errors showing up?

**Comment by NouGithub** [comment]
Thank you for the speedy reply.

Perhaps you should ELIM5 because after reinstalling it (just now), Tweak Tools is now reporting that there is an error loading the extension.... that's new.  And when I type `lg` I get an unknown command error.

Can we start over and pretend I am a total n00b, and perhaps you can hold my hand through an installation, if you don't mind?

Many thanks in either case, I suppose I've lived this long without session-restore, I can certainly go on. :)

**Comment by johannesjo** [comment]
I'll have another look on Monday. Thanks for the feedback! The lg command showing an error is weird though. Everything else is working fine though?

**Comment by NouGithub** [comment]
Not really.  I can't tell you why, but I have not been able to successful install it despite several attempts.  First the no indicator, which was the most common result, and now the error when trying to load it.

While I may be somewhat new to linux as a full-time daily machine, I work in IT and been working with OSs since pc-dos/unix/vax in the 80s.  But, for some reason, I am being challenged by your gnome extension! :)   

Anyway, thanks again, and have a nice weekend.

**Comment by johannesjo** [comment]
I gave this some further thought. So you have gnome shell installed correctly and other extensions are working fine? If you installed gnome shell then the `lg`command should definitely be available. It's important that you run it via ALT+F2 as the command is not available from the command line.

**Comment by NouGithub** [comment]
My sincere apologies for the delay in my reply, "life" happened over the weekend, so I am going to have to return to this at some other time in the future.  Many thanks again.
