### ISSUE TITLE
Cannot see any "screen" icon at the top bar

### ISSUE THREAD

**Issue by i0annis** [johannesjo/gnome-shell-extension-window-session-manager#23]
I am currently using Ubuntu 20.04.
Here is what I did (using terminal):
1) Installed nodejs (_sudo apt install nodejs_)
2) Installed npm (for some reason this package didn't come with nodejs)
3) Installed lwsm via npm: _npm install -g linux-window-session-manager_
4) I checked the /home/my-user-name/.local/share/gnome-shell/ directory, but the "extensions" folder did not exist so I created it (_mkdir ~/.local/share/gnome-shell/extensions_)
5) Inside the above dir I created a folder called "window-session-manager", downloaded the ZIP file from GitHub and extracted it in there. (Note: before that I tried the _git clone_ command but I had an error saying I do not have permission to access the files.)
6) Reboot - nothing.

I tried renaming the folder "../extensions/window-session-manager" to "../extensions/lwsm@johannes.super-productivity.com" to match with the instructions and rebooted, but that didn't make any difference. I still cannot see any icon at the top bar. (The _lwsm_ command works though.)

Any ideas?

**Comment by johannesjo** [comment]
Did you install the extension via:
```
cd tmp
git clone git@github.com:johannesjo/gnome-shell-extension-window-session-manager.git
mv gnome-shell-extension-window-session-manager /home/$(whoami)/.local/share/gnome-shell/extensions/lwsm@johannes.super-productivity.com
```
or directly form https://extensions.gnome.org/ ?

And does it show up under the gnome tweak tool?

**Comment by i0annis** [comment]
No, because the _git clone_ command did not work. 
I downloaded the files from [GitHub](https://github.com/johannesjo/gnome-shell-extension-window-session-manager) by clicking on the "Download ZIP" button. Then I right-clicked on the downloaded zip file and did "Extract-To" and chose the path ".../.local/share/gnome-shell/extensions/lwsm@johannes.super-productivity.com".

Nothing new appears in the gnome tweak tool.

**Comment by johannesjo** [comment]
In this case, maybe you can try installing it from here:
https://extensions.gnome.org/extension/1323/window-session-manager/
?

**Comment by i0annis** [comment]
Yep, I got it working! Thanks! 

Just one final question. I managed to install it this time using the browser add-on from "gnome-extensions", but if I manually downloaded the file from this page https://extensions.gnome.org/extension/1323/window-session-manager/ then where do I need to extract the contents to?

**Comment by johannesjo** [comment]
The path would need to be:
```
/home/$(whoami)/.local/share/gnome-shell/extensions/lwsm@johannes.super-productivity.com
```

**Comment by i0annis** [comment]
I get it now, it has to be the exact path. Thanks again for your help! :)
