### ISSUE TITLE
lswm is befuddled by Firefox v82

### ISSUE THREAD

**Issue by jim-moe** [johannesjo/gnome-shell-extension-window-session-manager#26]
lswm v4.0.2
firefox v82.0
gnome 3.36.7

The Window Session Manager no longer recognizes what Firefox is. FF recently updated to v82.0; lswm starts the app, and hangs waiting for some indication that FF has started. If I reset lswm (to clear the hang) and start FF again while an instance of FF is already running, a new instance of FF is started, and lswm hangs waiting for the new one.

**Comment by jim-moe** [comment]
Also... lswm seems to have a similar issue with gnome terminal windows.

**Comment by johannesjo** [comment]
Thank you very much for reporting. I am pretty busy atm with other stuff, but I would merge any PR fixing this. Best way to approach this is to check via `xprop` what changed for firefox in the most recent version and then to adjust the default settings of lwsm.

**Comment by jim-moe** [comment]
How do I use `xprop`? I tried `xprop -name firefox` with no success.

**Comment by johannesjo** [comment]
`xprop` + click on the firefox window should work.

**Comment by jim-moe** [comment]
Nope

**Comment by jim-moe** [comment]
`xprop + click` does work, just not on FF or gnome terminal.

**Comment by johannesjo** [comment]
Are you using wayland? lwsm does not work with wayland...

**Comment by jim-moe** [comment]
opensuse/gnome is using "wayland," a newer GUI. Could that be an issue?

**Comment by johannesjo** [comment]
yes! :)

**Comment by jim-moe** [comment]
There is no easy fix then?

**Comment by johannesjo** [comment]
You absolutely don't need to use wayland, this would be the easy fix :).

Apart from that: As wayland is very much still under development they have yet to provide the functionality to make something like lwsm work.

**Comment by johannesjo** [comment]
Just google for "Disable wayland" or something like that. Should be pretty straight forward I assume.

**Comment by jim-moe** [comment]
Okay. Thanks.

**Comment by johannesjo** [comment]
You're welcome!
