### ISSUE TITLE
Add a usage manual

### ISSUE THREAD

**Issue by Aran-Fey** [johannesjo/gnome-shell-extension-window-session-manager#3]
This extension has _no_ usage instructions whatsoever. All I know is that it's supposed to show an indicator _somewhere_. Problem is, __I can't find it__. It's impossible for me as a user to tell if this extension is broken or if it just has a terrible user interface that I'm not even able to find.

Please, at minimum just add a screenshot. It takes literally two minutes and does a good job of showing your users how it works.

**Comment by johannesjo** [comment]
Thanks for reporting. Makes a lot of sense! I'll add on a section to the readme.
