### ISSUE TITLE
ubuntu 21.10 - gnome 40

### ISSUE THREAD

**Issue by cytech** [johannesjo/gnome-shell-extension-window-session-manager#34]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

update extension to recognize gnome 40
## :pancakes: Action version

ubuntu 21.10 gnome-shell 4

## :tophat: workflow configuration

Your workflow configuration

## Steps To Reproduce

1.attempt to run extension under gnome 4
## :police_car: Expected behavior

to correct, add shell version to metadata.json
` "shell-version": [
    "40"
  ],`

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by johannesjo** [comment]
Thanks for opening this up. I'll try to provide an update soon.

**Comment by johannesjo** [comment]
The new version should be available now.
