### ISSUE TITLE
SESSION SNAPSHOTS

### ISSUE THREAD

**Issue by ibonomik** [johannesjo/gnome-shell-extension-window-session-manager#37]
Hi,I am using your extension with pleasure.Working well. 
I am using your program to record desktops sessions,too. 

Can we add a button for my every recorded entry which would record only one session in a moment of sessions. A button will freeze or snapshot that session.
So I can use most system recourses in my work and others can sleep.

Scenario: 
I am in eg; desktop 2 where my virtual machine is running and for a while I will need only this desktop. So I want to close the others. But I don't want to loose their open windows,tabs etc. 

At this moment: 
I can record my session as new session. And close them. This is too much job, lot of naming and deleting after records unnecessary any more
İf I record that moment as a session it will record everything also. So,mess..

Better Scenario:  After added this button. 
I can record,freeze or have a snapshot my other sessions with a click; the ones not necessary now,but will be. When I need, wake them again with the same button. And no need new record, new naming and deleting messes job.
If I start session from default record it will be start new session Frozen session kept.So,system recourses work for my job. 
Or, I can only record one desktop session to keep for after logout, reboot. 

As a result new record function will attach new record to already existing one and will save only windows belonging to this record entry.

Can we make Window Session Manager like this. thank you.

**Comment by johannesjo** [comment]
I am very sorry, but I don't understand you.

**Comment by ibonomik** [comment]
You are right.It is confused.And I realised it is not necessary. I can do what I asked to you with present structure.Forget what I asked.Thank you for this beatifull extension..

**Comment by ibonomik** [comment]
OK
