### ISSUE TITLE
Why don't you use rollup/webpack to pack all npm dependencies?

### ISSUE THREAD

**Issue by KSXGitHub** [johannesjo/gnome-shell-extension-window-session-manager#5]
Instead of asking users to install them independently

**Comment by johannesjo** [comment]
I tried doing this before. But it doesn't work because the gnome extension context is a little special unfortunately (no fs for example).

**Comment by KSXGitHub** [comment]
> (no fs for example)

so do browsers!

I've seen some guys use Webpack and ReactJS to build GTK+ apps.

**Comment by johannesjo** [comment]
Do you have some examples for that? That would be quite helpful!

**Comment by KSXGitHub** [comment]
[React GTK Example](https://www.youtube.com/watch?v=DHB1NgQc-bQ)

**Comment by johannesjo** [comment]
@KSXGitHub thanks for the example. Unfortunately gnome shell extensions are not really gtk applications, but gjs scripts that import a gtk layer. So this approach won't work here unfortunately. The only way I see this working is using lwsm as a binary and to run it as a shell command (and there was a former version which did exactly that, but which was to big in size to upload to the extensions website).
