### ISSUE TITLE
"lwsm: restore UNKNOWN ERROR"

### ISSUE THREAD

**Issue by NinjaTurtle007** [johannesjo/gnome-shell-extension-window-session-manager#8]
It opens couple on apps (on the wrong spots) and gives an error "lwsm: restore UNKNOWN ERROR"

It worked fine for a while (installed it today) but now gives that every time.

What are the possible reasons that can break it?

p.s.
not sure how this is relevant but it started happening after i tried it on Wayland.
Thats when it gave it for the first time (even with session saved under Wayland)

When I returned to Gnome with X later, it continued to give this error even with session saved under X.
Now gives it every time, for every session on either X or Wayland

**Comment by johannesjo** [comment]
Hey there! thanks for reporting. Is there some kind of stacktrace to this error? 

Also what's the output of:
```
echo GDK_BACKEND;
echo CLUTTER_BACKEND;
```

**Comment by NinjaTurtle007** [comment]
I don't know what is stacktrace neither where to input the echo commands :)

**Comment by johannesjo** [comment]
You need to open up a terminal. CTRL+ALT+T Should open one. There you need to type in the commands. And please also try: `lwsm restore´.

**Comment by NinjaTurtle007** [comment]
> ~$ lwsm restore
Generic Error in Main Handler Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:3788) UnhandledPromiseRejectionWarning: Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:3788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

as for the echo commands, writing them in the terminal is the first thing i tried but they just output the text after echo as expected, so i thought they are meant for somewhere else.



> $ echo GDK_BACKEND;
GDK_BACKEND

**Comment by johannesjo** [comment]
Hm. Seems like there is no session data (anymore). If you run `lwsm save` you should be able to use it again.

**Comment by NinjaTurtle007** [comment]
Even immediatelly after error the echo output is still blank
see

` lwsm restore
Generic Error in Main Handler Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13) Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:8913) UnhandledPromiseRejectionWarning: Error: could not load data
    at /usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:209:15
    at ReadFileContext.callback (/usr/local/lib/node_modules/linux-window-session-manager/node_modules/jfs/lib/Store.js:94:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
(node:8913) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8913) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
john@john:~$ echo GDK_BACKEND;
GDK_BACKEND
john@john:~$ echo CLUTTER_BACKEND;
CLUTTER_BACKEND
`

**Comment by NinjaTurtle007** [comment]
lwsm save created a profile called DEFAULT which seems to work

what other options i have for lwsm? for example saving profile with a specific name?

**Comment by johannesjo** [comment]
Glad that it works! You can find a complete documentation here: https://github.com/johannesjo/linux-window-session-manager
